config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks 
  resources :users, only: [:new, :create, :show, :destroy, :edit, :update]

  namespace :admin do
    resources :users
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord

  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings

end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true 
  validates :content, presence: true
  validates :period, presence: true

  belongs_to :user

  scope :search_title_and_status, 
  -> (search_title_and_status) {all.where("title LIKE ?","%#{search_title_and_status[0]}%").where(status: search_title_and_status[1])}
  scope :search_title, 
  -> (search_title) {all.where("title LIKE ?","%#{search_title}%")} 
  scope :search_status, 
  -> (search_status) {where(status: search_status)}
  scope :sort_period,
  -> {order(period: :desc)}
  scope :sort_priority,
  -> {order(priority: :asc)}
  scope :default,
  -> {all.order(created_at: "ASC")}
  
  enum status: {未着手:1,着手中:2,完了:3}
  enum priority: {高:1,中:2,低:3}
  
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

end

app/models/user.rb
class User < ApplicationRecord

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, length: { minimum: 6 }
  before_validation { email.downcase! }
  
  has_many :tasks, dependent: :destroy 
  
before_update :admin_cannot_update
before_destroy :admin_cannot_delete

private

def admin_cannot_update
  throw :abort if User.where(admin: true).count == 1 && self.admin_change == [true, false]
end

def admin_cannot_delete
  throw :abort if User.where(admin: true).count == 1 && self.admin == true
end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin

  def index
    @users = User.all.includes(:tasks)
  end

  def show
    @user = User.find(params[:id])
  end

  def new 
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to admin_users_path, notice: "新規ユーザーを登録しました"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザーを編集しました"
    else
      render :edit
    end
  end

  private

  def if_not_admin
    redirect_to tasks_path, notice: "管理者以外はアクセスできません" unless current_user.admin?
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  # before_action :skip_signup

  private

  def login_required
    redirect_to new_session_path unless current_user
  end

  # def skip_signup
  #   if current_user.present?
  #     redirect_to tasks_path
  #   else
  #     redirect_to new_task_path
  #   end
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    if params[:search_title].present? && params[:search_status].present?
      search_title_and_status = [params[:search_title],params[:search_status]]
      @tasks = current_user.tasks.search_title_and_status(search_title_and_status).page(params[:page]).per(5)
    elsif params[:search_title].present?
      search_title = params[:search_title]
      @tasks = current_user.tasks.search_title(search_title).page(params[:page]).per(5)
    elsif params[:search_status].present?
      search_status = params[:search_status]
      @tasks = current_user.tasks.search_status(search_status).page(params[:page]).per(5)
    elsif params[:sort_period]
      @tasks = current_user.tasks.sort_period.page(params[:page]).per(5)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.sort_priority.page(params[:page]).per(5)
    else
      @tasks = current_user.tasks.default.all.page(params[:page]).per(5)
      @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
    end
  end 

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :content, :period, :status, :priority, { label_ids: [] })
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def show
    if current_user == User.find(params[:id]) || User.find_by(admin: true)
    @user = User.find(params[:id])
    @tasks = Task.where(user_id: @user.id)
    else
      redirect_to tasks_path
    end
  end

  def new
    if current_user.present?
      redirect_to tasks_path
    else
    @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Edit user</h1>

<p>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :admin %>
  <%= f.select :admin, ([["admin",true],["user",false]]), {prompt: "選択してください"}, {class: 'task-select'}%>

  <%= f.submit "edit account" %>
<% end %>

app/views/admin/users/index.html.erb
<p>ユーザー一覧</p>

<%= link_to 'User create', new_admin_user_path %>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>User</th>
      <th>email</th>
      <th>task count</th>
      <th>administrater<th>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <% if user.admin? %>
          <td> admin </td>
        <% else %>
          <td> user </td>
        <% end %>
        <td><%= link_to 'Show', user, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>Create User</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%=form_with(model: [:admin, @user], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create account" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
>
  </body>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :period %>
    <%= form.date_field :period %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Task.statuses.keys.to_a), {prompt: "選択してください"}, {class: 'task-select'}%>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, options_for_select(Task.priorities.keys.to_a), {prompt: "選択してください"}, {class: 'task-select'}%>
  </div>

  <div class="field">
    <%= form.label :label %>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>TasksManagement</h1>

<h2>Search</h2>
<%= form_with url: tasks_path, method: :get, local: true do |form| %>
<div class="field" >

    <%= form.label :title %>
    <%= form.text_field :search_title, class: "form-control", style:"width:200px;"%>
  
  <br>
  
  <div class="field">
    <%= form.label :status %>
    <%= form.select :search_status, options_for_select(Task.statuses.keys.to_a), {prompt: "選択してください"}, {class: 'task-select'}%>
  </div>
  
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
  
  <br>

  <%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
  <%= form.submit 'Label Search', name: nil %>
<% end %>

<br>

<% end %>

<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title<br><br></th>
      <th>Content<br><br></th>
      <th>Period
      <br>
      <%= link_to '並替え', tasks_path(sort_period: "true") %>
      </th>
      <th>Status<br><br></th>
      <th>Priority
      <br>
      <%= link_to '並替え', tasks_path(sort_priority: "true") %>
      <br></th>
      <th>Label<br><br></th>
      <th>user<br><br></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= paginate @tasks %>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.period %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td>
        <% task.labels.each do |label| %>
        <%= label.name %>
        <% end %>
        </td>
        <td><%= task.user.name %></td>
        <td><%= link_to 'Show', task, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Period:</strong>
  <%= @task.period %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Labels:</strong>
  <%= @task.labels.pluck(:name) %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のタスク一覧</h1>

<p>メールアドレス: <%= @user.email %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title<br><br></th>
      <th>Content<br><br></th>
      <th>Period
      <br>
      <%= link_to '並替え', tasks_path(sort_period: "true") %>
      </th>
      <th>Status<br><br></th>
      <th>Priority
      <br>
      <%= link_to '並替え', tasks_path(sort_priority: "true") %>
      <br></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.period %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>